services:

  database:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
    # Stores PostgreSQL data permanently, so data is not lost when the container stops
      - postgres_data:/var/lib/postgresql/data
    # Runs SQL initialization files from the local ./sql folder

      - ./sql:/docker-entrypoint-initdb.d

  pipeline:
    image: raalshat21/weather-ml-image:v2
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./data/raw:/app/data/raw
      - ./model:/app/model
    command: python -m src.run_pipeline
  prediction:
    image: raalshat21/weather-ml-image:v2
    depends_on:
      - database
      - pipeline
    env_file:
      - .env
    volumes:
      - ./model:/app/model
    ports:
      - "8000:8000"
    command: uvicorn src.prediction:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data: